package com.splitia.service;

import com.splitia.dto.request.CreateInvoiceRequest;
import com.splitia.dto.request.CreatePaymentRequest;
import com.splitia.dto.request.UpdateInvoiceRequest;
import com.splitia.dto.response.InvoiceResponse;
import com.splitia.dto.response.PaymentResponse;
import com.splitia.exception.BadRequestException;
import com.splitia.exception.ResourceNotFoundException;
import com.splitia.mapper.InvoiceMapper;
import com.splitia.mapper.PaymentMapper;
import com.splitia.model.User;
import com.splitia.model.contact.Company;
import com.splitia.model.contact.Contact;
import com.splitia.model.enums.InvoiceStatus;
import com.splitia.model.finance.Invoice;
import com.splitia.model.finance.InvoiceItem;
import com.splitia.model.finance.Payment;
import com.splitia.repository.*;
import com.splitia.service.websocket.WebSocketNotificationService;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

@Service
@RequiredArgsConstructor
public class InvoiceService {
    
    private final InvoiceRepository invoiceRepository;
    private final UserRepository userRepository;
    private final ContactRepository contactRepository;
    private final CompanyRepository companyRepository;
    private final PaymentRepository paymentRepository;
    private final InvoiceMapper invoiceMapper;
    private final PaymentMapper paymentMapper;
    private final WebSocketNotificationService webSocketNotificationService;
    
    @Transactional(readOnly = true)
    public Page<InvoiceResponse> getAllInvoices(Pageable pageable, InvoiceStatus status, UUID contactId, UUID companyId) {
        if (status != null) {
            return invoiceRepository.findByStatus(status, pageable)
                    .map(invoiceMapper::toResponse);
        }
        if (contactId != null) {
            return invoiceRepository.findByContactId(contactId, pageable)
                    .map(invoiceMapper::toResponse);
        }
        if (companyId != null) {
            return invoiceRepository.findByCompanyId(companyId, pageable)
                    .map(invoiceMapper::toResponse);
        }
        return invoiceRepository.findAllActive(pageable)
                .map(invoiceMapper::toResponse);
    }
    
    @Transactional(readOnly = true)
    public InvoiceResponse getInvoiceById(UUID id) {
        Invoice invoice = invoiceRepository.findByIdAndDeletedAtIsNull(id)
                .orElseThrow(() -> new ResourceNotFoundException("Invoice", "id", id));
        return invoiceMapper.toResponse(invoice);
    }
    
    @Transactional
    public InvoiceResponse createInvoice(CreateInvoiceRequest request, UUID createdById) {
        User createdBy = userRepository.findByIdAndDeletedAtIsNull(createdById)
                .orElseThrow(() -> new ResourceNotFoundException("User", "id", createdById));
        
        Invoice invoice = new Invoice();
        invoice.setInvoiceNumber(request.getInvoiceNumber()); // Will be auto-generated by trigger if null
        invoice.setIssueDate(request.getIssueDate());
        invoice.setDueDate(request.getDueDate());
        invoice.setStatus(request.getStatus() != null ? request.getStatus() : InvoiceStatus.DRAFT);
        invoice.setSubtotal(request.getSubtotal());
        invoice.setTax(request.getTax() != null ? request.getTax() : BigDecimal.ZERO);
        invoice.setTotal(request.getTotal());
        invoice.setCurrency(request.getCurrency() != null ? request.getCurrency() : "USD");
        invoice.setNotes(request.getNotes());
        invoice.setCreatedBy(createdBy);
        
        if (request.getContactId() != null) {
            Contact contact = contactRepository.findByIdAndDeletedAtIsNull(request.getContactId())
                    .orElseThrow(() -> new ResourceNotFoundException("Contact", "id", request.getContactId()));
            invoice.setContact(contact);
        }
        
        if (request.getCompanyId() != null) {
            Company company = companyRepository.findByIdAndDeletedAtIsNull(request.getCompanyId())
                    .orElseThrow(() -> new ResourceNotFoundException("Company", "id", request.getCompanyId()));
            invoice.setCompany(company);
        }
        
        invoice = invoiceRepository.save(invoice);
        
        // Create invoice items
        List<InvoiceItem> items = new ArrayList<>();
        for (com.splitia.dto.request.CreateInvoiceItemRequest itemRequest : request.getItems()) {
            InvoiceItem item = new InvoiceItem();
            item.setDescription(itemRequest.getDescription());
            item.setQuantity(itemRequest.getQuantity());
            item.setUnitPrice(itemRequest.getUnitPrice());
            item.setTaxRate(itemRequest.getTaxRate() != null ? itemRequest.getTaxRate() : BigDecimal.ZERO);
            item.setTotal(itemRequest.getTotal());
            item.setInvoice(invoice);
            items.add(item);
        }
        invoice.setItems(items);
        invoice = invoiceRepository.save(invoice);
        
        InvoiceResponse response = invoiceMapper.toResponse(invoice);
        
        // Emit WebSocket event
        Map<String, Object> data = new HashMap<>();
        data.put("invoice", response);
        webSocketNotificationService.notifyInvoiceCreated(invoice.getId(), data, createdById);
        
        return response;
    }
    
    @Transactional
    public InvoiceResponse updateInvoice(UUID id, UpdateInvoiceRequest request) {
        Invoice invoice = invoiceRepository.findByIdAndDeletedAtIsNull(id)
                .orElseThrow(() -> new ResourceNotFoundException("Invoice", "id", id));
        
        if (request.getIssueDate() != null) invoice.setIssueDate(request.getIssueDate());
        if (request.getDueDate() != null) invoice.setDueDate(request.getDueDate());
        if (request.getStatus() != null) invoice.setStatus(request.getStatus());
        if (request.getSubtotal() != null) invoice.setSubtotal(request.getSubtotal());
        if (request.getTax() != null) invoice.setTax(request.getTax());
        if (request.getTotal() != null) invoice.setTotal(request.getTotal());
        if (request.getCurrency() != null) invoice.setCurrency(request.getCurrency());
        if (request.getNotes() != null) invoice.setNotes(request.getNotes());
        
        if (request.getContactId() != null) {
            Contact contact = contactRepository.findByIdAndDeletedAtIsNull(request.getContactId())
                    .orElseThrow(() -> new ResourceNotFoundException("Contact", "id", request.getContactId()));
            invoice.setContact(contact);
        }
        
        if (request.getCompanyId() != null) {
            Company company = companyRepository.findByIdAndDeletedAtIsNull(request.getCompanyId())
                    .orElseThrow(() -> new ResourceNotFoundException("Company", "id", request.getCompanyId()));
            invoice.setCompany(company);
        }
        
        // Update items if provided
        if (request.getItems() != null && !request.getItems().isEmpty()) {
            invoice.getItems().clear();
            for (com.splitia.dto.request.CreateInvoiceItemRequest itemRequest : request.getItems()) {
                InvoiceItem item = new InvoiceItem();
                item.setDescription(itemRequest.getDescription());
                item.setQuantity(itemRequest.getQuantity());
                item.setUnitPrice(itemRequest.getUnitPrice());
                item.setTaxRate(itemRequest.getTaxRate() != null ? itemRequest.getTaxRate() : BigDecimal.ZERO);
                item.setTotal(itemRequest.getTotal());
                item.setInvoice(invoice);
                invoice.getItems().add(item);
            }
        }
        
        invoice = invoiceRepository.save(invoice);
        InvoiceResponse response = invoiceMapper.toResponse(invoice);
        
        // Emit WebSocket event
        Map<String, Object> data = new HashMap<>();
        data.put("invoice", response);
        webSocketNotificationService.notifyInvoiceUpdated(invoice.getId(), data, getCurrentUserId());
        
        return response;
    }
    
    @Transactional
    public PaymentResponse addPayment(UUID invoiceId, CreatePaymentRequest request) {
        Invoice invoice = invoiceRepository.findByIdAndDeletedAtIsNull(invoiceId)
                .orElseThrow(() -> new ResourceNotFoundException("Invoice", "id", invoiceId));
        
        Payment payment = new Payment();
        payment.setAmount(request.getAmount());
        payment.setDate(request.getDate());
        payment.setPaymentMethod(request.getPaymentMethod());
        payment.setReference(request.getReference());
        payment.setCurrency(request.getCurrency() != null ? request.getCurrency() : invoice.getCurrency());
        payment.setNotes(request.getNotes());
        payment.setInvoice(invoice);
        
        payment = paymentRepository.save(payment);
        
        // Update invoice status if fully paid
        BigDecimal totalPaid = paymentRepository.getTotalPaidForInvoice(invoiceId);
        if (totalPaid.compareTo(invoice.getTotal()) >= 0) {
            invoice.setStatus(InvoiceStatus.PAID);
            invoiceRepository.save(invoice);
        } else if (invoice.getStatus() == InvoiceStatus.DRAFT) {
            invoice.setStatus(InvoiceStatus.SENT);
            invoiceRepository.save(invoice);
        }
        
        PaymentResponse response = paymentMapper.toResponse(payment);
        
        // Emit WebSocket events
        Map<String, Object> paymentData = new HashMap<>();
        paymentData.put("payment", response);
        webSocketNotificationService.notifyPaymentReceived(payment.getId(), paymentData, getCurrentUserId());
        
        if (invoice.getStatus() == InvoiceStatus.PAID) {
            Map<String, Object> invoiceData = new HashMap<>();
            invoiceData.put("invoice", invoiceMapper.toResponse(invoice));
            webSocketNotificationService.notifyInvoicePaid(invoice.getId(), invoiceData, getCurrentUserId());
        }
        
        return response;
    }
    
    @Transactional
    public void deleteInvoice(UUID id, boolean hardDelete) {
        if (hardDelete) {
            invoiceRepository.deleteById(id);
        } else {
            Invoice invoice = invoiceRepository.findByIdAndDeletedAtIsNull(id)
                    .orElseThrow(() -> new ResourceNotFoundException("Invoice", "id", id));
            invoice.setDeletedAt(LocalDateTime.now());
            invoiceRepository.save(invoice);
        }
    }
    
    private UUID getCurrentUserId() {
        try {
            org.springframework.security.core.Authentication authentication = 
                org.springframework.security.core.context.SecurityContextHolder.getContext().getAuthentication();
            if (authentication != null && authentication.getPrincipal() instanceof com.splitia.security.CustomUserDetails) {
                com.splitia.security.CustomUserDetails userDetails = 
                    (com.splitia.security.CustomUserDetails) authentication.getPrincipal();
                return userDetails.getUserId();
            }
        } catch (Exception e) {
            // If not authenticated, return null
        }
        return null;
    }
}

